### ISSUE TITLE
Web Workers in Firefox

### ISSUE THREAD

**Issue by are** [nkzawa/socket.io-stream#53]
socket.io-stream uses `FileReader` which is not supported in Firefox workers. Instead, `FileReaderSync` can be used. Is there any way to work around this?

**Comment by nkzawa** [comment]
It might be possible to polyfill `FileReader` if `FileReaderSync` has the same interface.

```
FileReader = FileReaderSync;
```
 
Anyway I think you can easily implement a stream which supports `FileReaderSync` since `FileReader` version is very simple. The current implementation is the following. 

https://github.com/nkzawa/socket.io-stream/blob/master/lib/blob-read-stream.js

**Comment by are-are-** [comment]
It turned out that both has the same interface, but latter is not instance of EventEmitter, thus is not emitting events.
